### ISSUE TITLE
Update Currency: Too easy to be rich

### ISSUE THREAD

**Issue by Doom306** [Ignite-Discord/Ignite-Java#16]
Add more work messages and earn messages... Fix the values of work also.

Reduce work fine also

Reduce all the earnings and divide every ones money by 10 (To make it fair for all)

**Comment by Doom306** [comment]
Seems good @HELL066 ?

**Comment by Overkill10117** [comment]
sounds good

**Comment by Doom306** [comment]
> sounds good

Nice

**Comment by Doom306** [comment]
Will make a new release this saturday regarding this

**Comment by HoursForever** [comment]
hello

**Comment by Doom306** [comment]
Nice account @HoursForever

**Comment by HoursForever** [comment]
wat? hahah

**Comment by Doom306** [comment]
@HoursForever is it ok?

**Comment by Doom306** [comment]
The to be update

**Comment by HoursForever** [comment]
i think its ok cuz were getting too much money

**Comment by Doom306** [comment]
Lol...... Anyways ur gonna be 10 mil

**Comment by HoursForever** [comment]
🤷

**Comment by Doom306** [comment]
Lol

**Comment by HoursForever** [comment]
a

**Comment by Doom306** [comment]
Howd you get that rich

**Comment by Doom306** [comment]
Blackjack?

**Comment by HoursForever** [comment]
gambling but im not that rich lol

**Comment by Overkill10117** [comment]
trivia

**Comment by HoursForever** [comment]
go ask duckie hahaha

**Comment by Doom306** [comment]
Oh wait....... ur not duckie........ i forgot...

**Comment by Doom306** [comment]
ahhhhhhh

**Comment by Doom306** [comment]
Hello @Overkill10117

**Comment by HoursForever** [comment]
what again??? :mike:

**Comment by Doom306** [comment]
uhhhhh i thought u have 100 mil lol

**Comment by HoursForever** [comment]
:mike:

**Comment by Doom306** [comment]
- [ ]

**Comment by Doom306** [comment]
- [ ] Yes

**Comment by HoursForever** [comment]
:bonk:

**Comment by Doom306** [comment]
Lol

**Comment by Doom306** [comment]
Suggest a feature here

**Comment by Doom306** [comment]
A completely new thing

**Comment by Doom306** [comment]
And try `ignthangman-start`

**Comment by Doom306** [comment]
Did it work? or dm you?

**Comment by HoursForever** [comment]
it didnt work

**Comment by Doom306** [comment]
hmmmm ok rip.....

**Comment by HoursForever** [comment]
a

**Comment by Doom306** [comment]
a

**Comment by HoursForever** [comment]
a

**Comment by Doom306** [comment]
a

**Comment by HoursForever** [comment]
a

**Comment by Overkill10117** [comment]
hi

**Comment by Doom306** [comment]
> hi

Hello @Overkill10117

**Comment by HoursForever** [comment]
hi

**Comment by Overkill10117** [comment]
hi

**Comment by HoursForever** [comment]
hi

**Comment by Doom306** [comment]
hi

**Comment by HoursForever** [comment]
hi

**Comment by Doom306** [comment]
hi

**Comment by HoursForever** [comment]
hi

**Comment by Doom306** [comment]
Check the other issues @HoursForever

**Comment by HoursForever** [comment]
ok

**Comment by HoursForever** [comment]
where lol

**Comment by Doom306** [comment]
@HoursForever https://github.com/Ignite-Discord/Ignite-Java/issues

**Comment by HoursForever** [comment]
Make a daily claim command worth 400k credits for Neptune people only    <-----  ???

**Comment by Doom306** [comment]
Edited @HoursForever

**Comment by Doom306** [comment]
To release in saturday
