### ISSUE TITLE
Hangman command is NOT working

### ISSUE THREAD

**Issue by Doom306** [Ignite-Discord/Ignite-Java#17]
Probably with the command name...... Also fix the BotManager.java Guild checking thingy
![image](https://user-images.githubusercontent.com/76986040/141731156-2f510ef4-1664-451a-9fbc-16e3da25ffa5.png)

**Comment by Overkill10117** [comment]
hrm

**Comment by Doom306** [comment]
Seems like a rare unreproducible bug
